### PR TITLE
Update to webpack 5 and elm-webpack-loader 8

### LINKED ISSUE #21: Update peer deps
The peerDeps declaration conflicts with using elm-webpack-loader on webapck5 systems. But it looks as though your code works perfectly fine with the 8.0.0 and its just the declaration that needs updating

### PR DESCRIPTION
**Pull request by robinheghan**
Fixes #21

### CODE REVIEW

**Comment by simonh1000** [comment]
time to merge?

**Comment by simonh1000** [comment]
Any update on this?

**Comment by rhoskal** [comment]
Bump... I'm willing to help if there are still items remaining to be done.

**Comment by mikeastock** [comment]
Also curious if this will get merged

**Comment by simonh1000** [comment]
This is stalled now for such a long time that I think it is worth considering forking, and asking @klazuka to deprecate this repo?

**Comment by ronanyeah** [comment]
Yeah lets get this sorted. I've been doing `--force` installs for like a year.

**Comment by ronanyeah** [comment]
I'm gonna publish a fork unless someone else really wants to?

**Comment by robinheghan** [comment]
> I'm gonna publish a fork unless someone else really wants to?

Go for it!

**Comment by kraklin** [comment]
@ronanyeah please do it, I was just thinking about doing the same as today a new co-worker wanted to do `npm install` and failed, which made me to revisit this bug and repository again

**Comment by kraklin** [comment]
@ronanyeah any progress on that given this PR is closed now?

**Comment by ronanyeah** [comment]
Yeah I'll get round to it at some point. I have backed up this fork.

**Comment by simonh1000** [comment]
Perhaps we should re-open this issue.

More importantly, which repo will own the fork in the future. It ought to be something with multiple owners - elm-community comes to mind

**Comment by ronanyeah** [comment]
I have published this: https://www.npmjs.com/package/elm-reloader
Here's an example usage: https://github.com/ronanyeah/elm-webpack

**Pull request closed without merging**
